### ISSUE TITLE
Not Splitting

### ISSUE THREAD

**Issue by JmarbinGG** [LordAsdi/SMO_AutoSplit#1]
Hi,

I installed this today, and the autosplitting for any% was working fine(fyi, I am using yuzu emulator). I left all my windows open and put my computer to sleep then woke it up again about a half hour later. Then I loaded a .lss file(it works fine with live split) and added all places to split. I tried a run, and it didn't detect me getting a moon or anything.  I have tried the following things to fix it:
1. deleting and downloading autosplitter again
2. reverting to the previous version
3. changing obs canvas and output to 16:9 resolution
4. making a new scene in obs

Also, I noticed that the preview in autosplitter was super scaled down, I am not sure if that has anything to do with it, here are some pics:
(If you cant see the diff, zoom in)
![Screenshot_20230114_044810](https://user-images.githubusercontent.com/108483439/212503959-a3b76a23-c655-4d75-a8f4-d1e40e99763f.png)
![Screenshot_20230114_044819](https://user-images.githubusercontent.com/108483439/212503960-0e1ecd4f-91d4-46fa-a680-f789dca90eae.png)

OS: windows 11
OBS Output: 1600x900
[application.log](https://github.com/LordAsdi/SMO_AutoSplit/files/10419207/application.log)

Thanks for any help in advance

**Comment by LordAsdi** [comment]
One issue is that the window border and status bars are visible in the video stream. Make sure to crop the video so only the game is visible.
According to the log file there was also an issue with the communication between smo autosplit and livesplit which I'll have to look into.

The preview has a maximum resolution of 853x480 since the auto splitters internal resolution is 640x480.

**Comment by JmarbinGG** [comment]
thanks for the help, i scaled the window as big as possible without cropping in OBS, and that fixed it. before, i had gone into full screen mode in yuzu, and that + the 16:10 made some black bars on the top and bottom.


if anyone else has this issue, change the OBS canvas size and the stream output(idk if that actually does anything or not, but better safe than sorry) to 16:9 and scale the window as big as possible(without cropping) in OBS





~~i’ll also make pull request to add that into faq~~

just reread the faq and saw the part about pixel perfect alignment and black borders
