### ISSUE TITLE
cloud kidom wont split

### ISSUE THREAD

**Issue by mrharryhd** [LordAsdi/SMO_AutoSplit#4]
evrvey thing else works but cloud kidom wont split

**Comment by LordAsdi** [comment]
Does your capture card output 60fps video?

**Comment by mrharryhd** [comment]
> Does your capture card output 60fps video?

yes it workd for all but cloud and the end of the run

**Comment by jljlspeedrunning** [comment]
Same here, my OBS Virtual Camera is 60fps, 1080p, etc. For some reason, the cutscene skip is not detected by the app, but a black screen is. But I can't really use a black screen, since it will also happen when I die in the fight. How can I do a split on Cloud Kingdom?

**Comment by LordAsdi** [comment]
Could you please send a screenshot of the application (like the one below) so I can try to figure out what could be causing the problem?

![image](https://github.com/user-attachments/assets/6730ba06-f13d-4ae6-b31e-e31911aec453)

**Comment by jljlspeedrunning** [comment]
![image](https://github.com/user-attachments/assets/e38e3d5f-3b0d-4d0d-8b85-b8eb70f8acbf)
![image](https://github.com/user-attachments/assets/b70f8912-e131-48be-b650-d0bdb6e26632)
![image](https://github.com/user-attachments/assets/88b2f538-6551-4da9-94a0-77ebe2b4320b)

(Acquired screenshots from a pre-recorded video)

According to the images, the video was 60fps, LiveSplit was connected, I made through 4 cutscenes without the app recognizing the cutscenes even once.

**Comment by LordAsdi** [comment]
The thing which is probably causing the problem is that the black levels are raised slightly above 0. Can you make sure that the "Color Range" in the capture card properties in OBS is set to "Limited". When I set it to "Full" I could observe the same behavior as you described.
![image](https://github.com/user-attachments/assets/773b34ba-a0a0-4289-8b4a-36fadfa04f53)

**Comment by jljlspeedrunning** [comment]
I think they all worked out, thanks!

**Comment by jljlspeedrunning** [comment]
I also realized that when color range is set to "limited", other minor details cannot be distinguished, but lowering the brightness through video configuration on OBS seemed to do the trick.
